name: CI/CD

on:
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: go test -v ./...
        
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: <version>

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan
        env:
          TF_LOG: DEBUG
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
          TF_VAR_do_spaces_access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          TF_VAR_do_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
          TF_VAR_do_space_name: ${{ secrets.DO_SPACE_NAME }}
          TF_VAR_discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: tfplan