name: CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - 'terraform/**'

jobs:
    terraform_apply:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
  
        - name: Terraform Init
          run: terraform -chdir=terraform init -backend-config="access_key=${{ secrets.DO_SPACES_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET_KEY }}" -backend-config="bucket=tfstate-echobase"
  
        - name: Download Terraform Plan Artifact
          uses: actions/download-artifact@v2
          with:
            name: tfplan
  
        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan

    cleanup:
      runs-on: ubuntu-latest
      needs: terraform_apply
      steps:
        - name: Clean up Terraform resources
          run: |
            rm -rf tfplan
