name: Terraform Apply

on:
  pull_request:
    types:
      - closed
    branches:
      - main

defaults:
  run:
    working-directory: terraform

jobs:
  terraform_apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="access_key=${{ secrets.DO_SPACES_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET_KEY }}" -backend-config="bucket=tfstate-echobase"

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_LOG: DEBUG
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
          TF_VAR_do_spaces_access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          TF_VAR_do_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
          TF_VAR_do_space_name: ${{ secrets.DO_SPACE_NAME }}
          TF_VAR_discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
